# Generated by Django 4.2.3 on 2023-08-14 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0005_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, default='', related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
