# Generated by Django 4.2.3 on 2023-07-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
