# Generated by Django 4.2.3 on 2023-08-13 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0014_post_bookmarks_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, default=False, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
